POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "How to write a unit test with Jest",
  "description": "This is a description of the video about how to write a unit test with Jest",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/5ca82230-a03e-44ab-b9a6-a46222149523
Content-Type: application/json

{
  "title": "How to write a integration test with Jest and Testing Library",
  "description": "This is a description of the video about how to write a integration test with Jest and Testing Library",
  "duration": 240
}

###

DELETE http://localhost:3333/videos/5ca82230-a03e-44ab-b9a6-a46222149523