POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "How to write a unit test with Jest",
  "description": "This is a description of the video about how to write a unit test with Jest",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=how

###

PUT http://localhost:3333/videos/6c14056e-4cf6-4ed6-bef5-0755ee1bf1ae
Content-Type: application/json

{
  "title": "Video 2285",
  "description": "This is a description of Video 2285",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/6c14056e-4cf6-4ed6-bef5-0755ee1bf1ae