POST https://node-api-learning-ehgn.onrender.com/videos
Content-Type: application/json

{
  "title": "How to write a Components in React Js with TypeScipt",
  "description": "This is a description of the video about how to write a Components in React Js with TypeScipt",
  "duration": 180
}

###

GET https://node-api-learning-ehgn.onrender.com/videos

###

PUT https://node-api-learning-ehgn.onrender.com/videos/7c4410d5-d245-4656-a5ea-e6fa7ecdcfc3
Content-Type: application/json

{
  "title": "How to write a integration test with Jest and Testing Library",
  "description": "This is a description of the video about how to write a integration test with Jest and Testing Library",
  "duration": 240
}

###

DELETE https://node-api-learning-ehgn.onrender.com/videos/7c4410d5-d245-4656-a5ea-e6fa7ecdcfc3